// @ts-nocheck
import "./globals.css";
import Navbar from "@/components/navbar";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { Kanit } from "next/font/google";
import Provider from "./providers";

config.autoAddCss = false;
const kanit = Kanit({ weight: "400", subsets: ["latin"] });

export const metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

interface IProps {
 children: React.ReactNode;
 session: any;
}

export default function RootLayout({ children, session }: IProps) {
 return (
  <html lang="en">
   <body
    className={`${kanit.className}bg-slate-100 dark:bg-slate-900 text-slate-950 dark:text-slate-50`}
   >
    <Provider session={session}>
     <div className="w-[70%] ml-[50%] translate-x-[-50%] py-5">
      <Navbar />
      {children}
     </div>
    </Provider>
   </body>
  </html>
 );
}
